//
// DefaultAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DefaultAPI {

    /**
     * enum for parameter category
     */
    public enum Category_topHeadlinesGet: String, CaseIterable {
        case general = "general"
        case world = "world"
        case nation = "nation"
        case business = "business"
        case technology = "technology"
        case entertainment = "entertainment"
        case sports = "sports"
        case science = "science"
        case health = "health"
    }

    /**
     Top Headlines Endpoint
     
     - parameter category: (query) This parameter allows you to change the category for the request. 
     - parameter apikey: (query) API Key (is always {your_apikey}) 
     - parameter max: (query) This parameter allows you to specify the number of news articles returned by the API. The minimum value of this parameter is 1 and the maximum value is 100. 
     - parameter page: (query) This parameter allows you to control the pagination of the results returned by the API. The paging behavior is closely related to the value of the max parameter. 
     - returns: Articles
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func topHeadlinesGet(category: Category_topHeadlinesGet, apikey: String, max: Int, page: Int) async throws -> Articles {
        return try await topHeadlinesGetWithRequestBuilder(category: category, apikey: apikey, max: max, page: page).execute().body
    }

    /**
     Top Headlines Endpoint
     - GET /top-headlines
     - parameter category: (query) This parameter allows you to change the category for the request. 
     - parameter apikey: (query) API Key (is always {your_apikey}) 
     - parameter max: (query) This parameter allows you to specify the number of news articles returned by the API. The minimum value of this parameter is 1 and the maximum value is 100. 
     - parameter page: (query) This parameter allows you to control the pagination of the results returned by the API. The paging behavior is closely related to the value of the max parameter. 
     - returns: RequestBuilder<Articles> 
     */
    open class func topHeadlinesGetWithRequestBuilder(category: Category_topHeadlinesGet, apikey: String, max: Int, page: Int) -> RequestBuilder<Articles> {
        let localVariablePath = "/top-headlines"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "category": (wrappedValue: category.encodeToJSON(), isExplode: true),
            "apikey": (wrappedValue: apikey.encodeToJSON(), isExplode: true),
            "max": (wrappedValue: max.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Articles>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
