//
// Articles.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Articles: Codable, JSONEncodable, Hashable {

    public var totalArticles: Int?
    public var articles: [ArticlesArticlesInner]?

    public init(totalArticles: Int? = nil, articles: [ArticlesArticlesInner]? = nil) {
        self.totalArticles = totalArticles
        self.articles = articles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalArticles
        case articles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalArticles, forKey: .totalArticles)
        try container.encodeIfPresent(articles, forKey: .articles)
    }
}

