//
// ArticlesArticlesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArticlesArticlesInner: Codable, JSONEncodable, Hashable {

    public var id = UUID()
    public var title: String?
    public var description: String?
    public var content: String?
    public var url: String?
    public var image: String?
    public var publishedAt: String?
    public var source: ArticlesArticlesInnerSource?

    public init(title: String? = nil, description: String? = nil, content: String? = nil, url: String? = nil, image: String? = nil, publishedAt: String? = nil, source: ArticlesArticlesInnerSource? = nil) {
        self.title = title
        self.description = description
        self.content = content
        self.url = url
        self.image = image
        self.publishedAt = publishedAt
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case description
        case content
        case url
        case image
        case publishedAt
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(publishedAt, forKey: .publishedAt)
        try container.encodeIfPresent(source, forKey: .source)
    }
}

